version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: npm install
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   environment:
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true
  #   command: ["npm", "run", "test"]